/*
 * This file is part of OpenTTD.
 * OpenTTD is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, version 2.
 * OpenTTD is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with OpenTTD. If not, see <https://www.gnu.org/licenses/old-licenses/gpl-2.0>.
 */

/**
 * @file seaplane_movement.h Movement data and state machines of the TGTFTD seaplane terminals.
 * GENERATED by tools/seaplane_fta.py -- edit that script and re-run it instead of editing this file.
 *
 * Every runway is split in a landing half and a departure half with their own blocks, so a seaplane can
 * land while another one takes off. Berths and hangars are where the land airports have them.
 */

#ifndef SEAPLANE_MOVEMENT_H
#define SEAPLANE_MOVEMENT_H

/** Seaplane version of the country airfield. */
static const AirportMovingData _airport_moving_data_seaplane_country[17] = {
	{   53,    3, {AirportMovingDataFlag::ExactPosition},                                     Direction::SE }, // 00 In hangar
	{   53,   27, {},                                                                         Direction::N  }, // 01 Outside the hangar
	{   32,   23, {AirportMovingDataFlag::ExactPosition},                                     Direction::NW }, // 02 Berth 1
	{   10,   23, {AirportMovingDataFlag::ExactPosition},                                     Direction::NW }, // 03 Berth 2
	{   32,   31, {},                                                                         Direction::N  }, // 04 In front of berth 1
	{   10,   31, {},                                                                         Direction::N  }, // 05 In front of berth 2
	{   26,   40, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 06 Line up: start of the departure half
	{    3,   40, {AirportMovingDataFlag::NoSpeedClamp},                                      Direction::N  }, // 07 End of the departure run
	{  -60,   40, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Takeoff},      Direction::N  }, // 08 Take off
	{  110,   40, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 09 Final approach fix
	{   60,   40, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Land},         Direction::N  }, // 10 Touch down at the start of the landing half
	{   40,   40, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Brake},        Direction::N  }, // 11 Stop, holding short of the departure half
	{   46,   32, {},                                                                         Direction::N  }, // 12 Leave the landing half
	{   14,  124, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 13 Holding (north-east)
	{   14,    9, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 14 Holding (north-west)
	{  167,    9, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 15 Holding (south-west)
	{  176,   36, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 16 Holding (south)
};
static const uint8_t _airport_terminal_seaplane_country[] = { 1, 2 };
static const uint8_t _airport_entries_seaplane_country[] = { 14, 13, 16, 15 };
static const AirportFTAbuildup _airport_fta_seaplane_country[] = {
	{  0, HANGAR, AirportBlock::Nothing, 1 },
	{  1, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, {  1, HANGAR, {}, 0 }, {  1, TO_ALL, {}, 4 },
	{  2, TERM1, AirportBlock::Term1, 4 },
	{  3, TERM2, AirportBlock::Term2, 5 },
	{  4, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, {  4, TERM1, AirportBlock::Term1, 2 }, {  4, TERM2, {}, 5 }, {  4, HANGAR, {}, 1 }, {  4, TAKEOFF, {}, 6 }, {  4, TO_ALL, {}, 1 },
	{  5, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, {  5, TERM2, AirportBlock::Term2, 3 }, {  5, TO_ALL, {}, 4 },
	{  6, TAKEOFF, AirportBlock::SeaRunway1Depart, 7 },
	{  7, STARTTAKEOFF, AirportBlock::SeaRunway1Depart, 8 },
	{  8, ENDTAKEOFF, AirportBlock::Nothing, 0 },
	{  9, FLYING, AirportBlock::Nothing, 13 }, {  9, LANDING, AirportBlock::SeaRunway1Exit, 10 },
	{ 10, LANDING, AirportBlock::SeaRunway1Land, 11 },
	{ 11, TO_ALL, AirportBlock::SeaRunway1Land, 12 },
	{ 12, ENDLANDING, AirportBlock::SeaRunway1Exit, 1 }, { 12, TO_ALL, {}, 1 },
	{ 13, TO_ALL, AirportBlock::Nothing, 14 },
	{ 14, TO_ALL, AirportBlock::Nothing, 15 },
	{ 15, TO_ALL, AirportBlock::Nothing, 16 },
	{ 16, TO_ALL, AirportBlock::Nothing, 9 },
	{ MAX_ELEMENTS, TO_ALL, {}, 0 } // end marker. DO NOT REMOVE
};

/** Seaplane version of the commuter airfield. */
static const AirportMovingData _airport_moving_data_seaplane_commuter[22] = {
	{   69,    3, {AirportMovingDataFlag::ExactPosition},                                     Direction::SE }, // 00 In hangar
	{   72,   22, {},                                                                         Direction::N  }, // 01 Outside the hangar
	{    8,   22, {},                                                                         Direction::N  }, // 02 West end of the taxi lane
	{   24,   36, {AirportMovingDataFlag::ExactPosition},                                     Direction::SE }, // 03 Berth 1
	{   40,   36, {AirportMovingDataFlag::ExactPosition},                                     Direction::SE }, // 04 Berth 2
	{   56,   36, {AirportMovingDataFlag::ExactPosition},                                     Direction::SE }, // 05 Berth 3
	{   24,   22, {},                                                                         Direction::N  }, // 06 Taxi lane at berth 1
	{   40,   22, {},                                                                         Direction::N  }, // 07 Taxi lane at berth 2
	{   56,   22, {},                                                                         Direction::N  }, // 08 Taxi lane at berth 3
	{    8,   40, {},                                                                         Direction::N  }, // 09 Holding point in the west column
	{    8,   54, {},                                                                         Direction::N  }, // 10 Enter the departure half
	{   36,   54, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 11 Line up: start of the departure half
	{    5,   54, {AirportMovingDataFlag::NoSpeedClamp},                                      Direction::N  }, // 12 End of the departure run
	{  -60,   54, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Takeoff},      Direction::N  }, // 13 Take off
	{  130,   54, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 14 Final approach fix
	{   76,   54, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Land},         Direction::N  }, // 15 Touch down at the start of the landing half
	{   46,   54, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Brake},        Direction::N  }, // 16 Stop, holding short of the departure half
	{   72,   46, {},                                                                         Direction::N  }, // 17 Leave the landing half to the east column
	{   16,  100, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 18 Holding (north-east)
	{   16,   15, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 19 Holding (north-west)
	{  130,   15, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 20 Holding (south-west)
	{  150,   48, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 21 Holding (south)
};
static const uint8_t _airport_terminal_seaplane_commuter[] = { 1, 3 };
static const uint8_t _airport_entries_seaplane_commuter[] = { 19, 18, 21, 20 };
static const AirportFTAbuildup _airport_fta_seaplane_commuter[] = {
	{  0, HANGAR, AirportBlock::Nothing, 1 },
	{  1, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, {  1, HANGAR, {}, 0 }, {  1, TO_ALL, {}, 8 },
	{  2, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, {  2, TAKEOFF, {}, 9 }, {  2, TO_ALL, {}, 6 },
	{  3, TERM1, AirportBlock::Term1, 6 },
	{  4, TERM2, AirportBlock::Term2, 7 },
	{  5, TERM3, AirportBlock::Term3, 8 },
	{  6, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, {  6, TERM1, AirportBlock::Term1, 3 }, {  6, TAKEOFF, {}, 2 }, {  6, TO_ALL, {}, 7 },
	{  7, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, {  7, TERM2, AirportBlock::Term2, 4 }, {  7, TERM1, {}, 6 }, {  7, TAKEOFF, {}, 6 }, {  7, TO_ALL, {}, 8 },
	{  8, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, {  8, TERM3, AirportBlock::Term3, 5 }, {  8, HANGAR, {}, 1 }, {  8, TO_ALL, {}, 7 },
	{  9, TO_ALL, AirportBlock::SeaHold1, 10 },
	{ 10, TO_ALL, AirportBlock::SeaRunway1Depart, 11 },
	{ 11, TAKEOFF, AirportBlock::SeaRunway1Depart, 12 },
	{ 12, STARTTAKEOFF, AirportBlock::SeaRunway1Depart, 13 },
	{ 13, ENDTAKEOFF, AirportBlock::Nothing, 0 },
	{ 14, FLYING, AirportBlock::Nothing, 18 }, { 14, LANDING, AirportBlock::SeaRunway1Exit, 15 },
	{ 15, LANDING, AirportBlock::SeaRunway1Land, 16 },
	{ 16, TO_ALL, AirportBlock::SeaRunway1Land, 17 },
	{ 17, ENDLANDING, AirportBlock::SeaRunway1Exit, 1 }, { 17, TO_ALL, {}, 1 },
	{ 18, TO_ALL, AirportBlock::Nothing, 19 },
	{ 19, TO_ALL, AirportBlock::Nothing, 20 },
	{ 20, TO_ALL, AirportBlock::Nothing, 21 },
	{ 21, TO_ALL, AirportBlock::Nothing, 14 },
	{ MAX_ELEMENTS, TO_ALL, {}, 0 } // end marker. DO NOT REMOVE
};

/** Seaplane version of the city airport. */
static const AirportMovingData _airport_moving_data_seaplane_city[20] = {
	{   85,    3, {AirportMovingDataFlag::ExactPosition},                                     Direction::SE }, // 00 In hangar
	{   85,   22, {},                                                                         Direction::N  }, // 01 Outside the hangar
	{   26,   41, {AirportMovingDataFlag::ExactPosition},                                     Direction::SW }, // 02 Berth 1
	{   56,   22, {AirportMovingDataFlag::ExactPosition},                                     Direction::SE }, // 03 Berth 2
	{   38,    8, {AirportMovingDataFlag::ExactPosition},                                     Direction::SW }, // 04 Berth 3
	{   65,    6, {},                                                                         Direction::N  }, // 05 In front of berths 2 and 3
	{   80,   27, {},                                                                         Direction::N  }, // 06 Taxiway to berths 2 and 3
	{   50,   62, {},                                                                         Direction::N  }, // 07 Middle of the harbour
	{   40,   74, {},                                                                         Direction::N  }, // 08 Holding point before the departure half
	{   42,   86, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 09 Line up: start of the departure half
	{    3,   86, {AirportMovingDataFlag::NoSpeedClamp},                                      Direction::N  }, // 10 End of the departure run
	{  -60,   86, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Takeoff},      Direction::N  }, // 11 Take off
	{  140,   86, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 12 Final approach fix
	{   90,   86, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Land},         Direction::N  }, // 13 Touch down at the start of the landing half
	{   56,   86, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Brake},        Direction::N  }, // 14 Stop, holding short of the departure half
	{   64,   73, {},                                                                         Direction::N  }, // 15 Leave the landing half
	{   14,  140, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 16 Holding (north-east)
	{   14,   10, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 17 Holding (north-west)
	{  170,   10, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 18 Holding (south-west)
	{  180,   60, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 19 Holding (south)
};
static const uint8_t _airport_terminal_seaplane_city[] = { 1, 3 };
static const uint8_t _airport_entries_seaplane_city[] = { 17, 16, 19, 18 };
static const AirportFTAbuildup _airport_fta_seaplane_city[] = {
	{  0, HANGAR, AirportBlock::Nothing, 1 },
	{  1, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, {  1, HANGAR, {}, 0 }, {  1, TERM2, {}, 6 }, {  1, TERM3, {}, 6 }, {  1, TO_ALL, {}, 7 },
	{  2, TERM1, AirportBlock::Term1, 7 },
	{  3, TERM2, AirportBlock::Term2, 6 },
	{  4, TERM3, AirportBlock::Term3, 5 },
	{  5, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, {  5, TERM2, AirportBlock::Term2, 3 }, {  5, TERM3, AirportBlock::Term3, 4 }, {  5, TO_ALL, {}, 6 },
	{  6, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, {  6, TERM2, AirportBlock::Term2, 3 }, {  6, TERM3, {}, 5 }, {  6, HANGAR, {}, 1 }, {  6, TO_ALL, {}, 7 },
	{  7, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, {  7, TERM1, AirportBlock::Term1, 2 }, {  7, TAKEOFF, {}, 8 }, {  7, HANGAR, {}, 1 }, {  7, TO_ALL, {}, 6 },
	{  8, TO_ALL, AirportBlock::SeaHold1, 9 },
	{  9, TAKEOFF, AirportBlock::SeaRunway1Depart, 10 },
	{ 10, STARTTAKEOFF, AirportBlock::SeaRunway1Depart, 11 },
	{ 11, ENDTAKEOFF, AirportBlock::Nothing, 0 },
	{ 12, FLYING, AirportBlock::Nothing, 16 }, { 12, LANDING, AirportBlock::SeaRunway1Exit, 13 },
	{ 13, LANDING, AirportBlock::SeaRunway1Land, 14 },
	{ 14, TO_ALL, AirportBlock::SeaRunway1Land, 15 },
	{ 15, ENDLANDING, AirportBlock::SeaRunway1Exit, 7 }, { 15, TO_ALL, {}, 7 },
	{ 16, TO_ALL, AirportBlock::Nothing, 17 },
	{ 17, TO_ALL, AirportBlock::Nothing, 18 },
	{ 18, TO_ALL, AirportBlock::Nothing, 19 },
	{ 19, TO_ALL, AirportBlock::Nothing, 12 },
	{ MAX_ELEMENTS, TO_ALL, {}, 0 } // end marker. DO NOT REMOVE
};

/** Seaplane version of the metropolitan airport. */
static const AirportMovingData _airport_moving_data_seaplane_metropolitan[33] = {
	{   85,    3, {AirportMovingDataFlag::ExactPosition},                                     Direction::SE }, // 00 In hangar
	{   85,   22, {},                                                                         Direction::N  }, // 01 Outside the hangar
	{   26,   41, {AirportMovingDataFlag::ExactPosition},                                     Direction::SW }, // 02 Berth 1
	{   56,   22, {AirportMovingDataFlag::ExactPosition},                                     Direction::SE }, // 03 Berth 2
	{   38,    8, {AirportMovingDataFlag::ExactPosition},                                     Direction::SW }, // 04 Berth 3
	{   65,    6, {},                                                                         Direction::N  }, // 05 In front of berths 2 and 3
	{   80,   27, {},                                                                         Direction::N  }, // 06 Taxiway to berths 2 and 3
	{   50,   54, {},                                                                         Direction::N  }, // 07 Middle of the harbour
	{   40,   61, {},                                                                         Direction::N  }, // 08 Holding point before the departure half of runway 2
	{   42,   69, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 09 Line up on runway 2
	{    3,   69, {AirportMovingDataFlag::NoSpeedClamp},                                      Direction::N  }, // 10 End of the departure run on runway 2
	{  -60,   69, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Takeoff},      Direction::N  }, // 11 Take off from runway 2
	{   26,   58, {},                                                                         Direction::N  }, // 12 Holding point before crossing runway 2
	{   26,   70, {},                                                                         Direction::N  }, // 13 Crossing the departure half of runway 2
	{   30,   78, {},                                                                         Direction::N  }, // 14 Holding point before the departure half of runway 1
	{   42,   85, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 15 Line up on runway 1
	{    3,   85, {AirportMovingDataFlag::NoSpeedClamp},                                      Direction::N  }, // 16 End of the departure run on runway 1
	{  -60,   85, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Takeoff},      Direction::N  }, // 17 Take off from runway 1
	{  150,   77, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 18 Final approach: choose a free landing half
	{  128,   85, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 19 Final approach to runway 1
	{   90,   85, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Land},         Direction::N  }, // 20 Touch down on runway 1
	{   56,   85, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Brake},        Direction::N  }, // 21 Stop on runway 1, holding short of its departure half
	{   62,   78, {},                                                                         Direction::N  }, // 22 Leave runway 1
	{   64,   69, {},                                                                         Direction::N  }, // 23 Crossing the landing half of runway 2
	{  128,   69, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 24 Final approach to runway 2
	{   90,   69, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Land},         Direction::N  }, // 25 Touch down on runway 2
	{   56,   69, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Brake},        Direction::N  }, // 26 Stop on runway 2, holding short of its departure half
	{   60,   61, {},                                                                         Direction::N  }, // 27 Leave runway 2
	{   14,  140, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 28 Holding (north-east)
	{   14,   10, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 29 Holding (north-west)
	{  170,   10, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 30 Holding (south-west)
	{  180,   50, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 31 Holding (south)
	{   66,   60, {},                                                                         Direction::N  }, // 32 Wait north of runway 2 after crossing it
};
static const uint8_t _airport_terminal_seaplane_metropolitan[] = { 1, 3 };
static const uint8_t _airport_entries_seaplane_metropolitan[] = { 29, 28, 31, 30 };
static const AirportFTAbuildup _airport_fta_seaplane_metropolitan[] = {
	{  0, HANGAR, AirportBlock::Nothing, 1 },
	{  1, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, {  1, HANGAR, {}, 0 }, {  1, TERM2, {}, 6 }, {  1, TERM3, {}, 6 }, {  1, TO_ALL, {}, 7 },
	{  2, TERM1, AirportBlock::Term1, 7 }, {  2, TAKEOFF, {}, 12 }, {  2, TO_ALL, {}, 7 },
	{  3, TERM2, AirportBlock::Term2, 6 },
	{  4, TERM3, AirportBlock::Term3, 5 },
	{  5, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, {  5, TERM2, AirportBlock::Term2, 3 }, {  5, TERM3, AirportBlock::Term3, 4 }, {  5, TO_ALL, {}, 6 },
	{  6, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, {  6, TERM2, AirportBlock::Term2, 3 }, {  6, TERM3, {}, 5 }, {  6, HANGAR, {}, 1 }, {  6, TO_ALL, {}, 7 },
	{  7, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, {  7, TERM1, AirportBlock::Term1, 2 }, {  7, TAKEOFF, {}, 8 }, {  7, HANGAR, {}, 1 }, {  7, TO_ALL, {}, 6 },
	{  8, TO_ALL, AirportBlock::SeaHold1, 9 },
	{  9, TAKEOFF, AirportBlock::SeaRunway2Depart, 10 },
	{ 10, STARTTAKEOFF, AirportBlock::SeaRunway2Depart, 11 },
	{ 11, ENDTAKEOFF, AirportBlock::Nothing, 0 },
	{ 12, TO_ALL, AirportBlock::SeaHold2, 13 },
	{ 13, TO_ALL, AirportBlock::SeaRunway2Depart, 14 },
	{ 14, TO_ALL, AirportBlock::SeaHold3, 15 },
	{ 15, TAKEOFF, AirportBlock::SeaRunway1Depart, 16 },
	{ 16, STARTTAKEOFF, AirportBlock::SeaRunway1Depart, 17 },
	{ 17, ENDTAKEOFF, AirportBlock::Nothing, 0 },
	{ 18, FLYING, AirportBlock::Nothing, 28 }, { 18, LANDING, AirportBlock::SeaRunway1Exit, 19 }, { 18, LANDING, AirportBlock::SeaRunway2Exit, 24 },
	{ 19, TO_ALL, AirportBlock::SeaRunway1Land, 20 },
	{ 20, LANDING, AirportBlock::SeaRunway1Land, 21 },
	{ 21, TO_ALL, AirportBlock::SeaRunway1Land, 22 },
	{ 22, ENDLANDING, AirportBlock::SeaRunway1Exit, 23 }, { 22, TO_ALL, {}, 23 },
	{ 23, TO_ALL, AirportBlock::SeaRunway2Land, 32 },
	{ 24, TO_ALL, AirportBlock::SeaRunway2Land, 25 },
	{ 25, LANDING, AirportBlock::SeaRunway2Land, 26 },
	{ 26, TO_ALL, AirportBlock::SeaRunway2Land, 27 },
	{ 27, ENDLANDING, AirportBlock::SeaRunway2Exit, 7 }, { 27, TO_ALL, {}, 7 },
	{ 28, TO_ALL, AirportBlock::Nothing, 29 },
	{ 29, TO_ALL, AirportBlock::Nothing, 30 },
	{ 30, TO_ALL, AirportBlock::Nothing, 31 },
	{ 31, TO_ALL, AirportBlock::Nothing, 18 },
	{ 32, TO_ALL, AirportBlock::SeaTaxi2, 7 },
	{ MAX_ELEMENTS, TO_ALL, {}, 0 } // end marker. DO NOT REMOVE
};

/** Seaplane version of the international airport. */
static const AirportMovingData _airport_moving_data_seaplane_international[42] = {
	{    7,   55, {AirportMovingDataFlag::ExactPosition},                                     Direction::SE }, // 00 In hangar 1
	{  100,   21, {AirportMovingDataFlag::ExactPosition},                                     Direction::SE }, // 01 In hangar 2
	{    7,   70, {},                                                                         Direction::N  }, // 02 Outside hangar 1
	{  100,   36, {},                                                                         Direction::N  }, // 03 Outside hangar 2
	{   38,   70, {AirportMovingDataFlag::ExactPosition},                                     Direction::SW }, // 04 Berth 1
	{   38,   54, {AirportMovingDataFlag::ExactPosition},                                     Direction::SW }, // 05 Berth 2
	{   38,   38, {AirportMovingDataFlag::ExactPosition},                                     Direction::SW }, // 06 Berth 3
	{   70,   70, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 07 Berth 4
	{   70,   54, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 08 Berth 5
	{   70,   38, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 09 Berth 6
	{   22,   87, {},                                                                         Direction::N  }, // 10 South-west corner of the taxiways
	{   60,   87, {},                                                                         Direction::N  }, // 11 South taxiway
	{   86,   87, {},                                                                         Direction::N  }, // 12 South-east corner of the taxiways
	{   86,   70, {},                                                                         Direction::N  }, // 13 In front of berth 4
	{   86,   54, {},                                                                         Direction::N  }, // 14 In front of berth 5
	{   86,   38, {},                                                                         Direction::N  }, // 15 In front of berth 6
	{   86,   22, {},                                                                         Direction::N  }, // 16 North-east corner of the taxiways
	{   60,   22, {},                                                                         Direction::N  }, // 17 North taxiway
	{   22,   22, {},                                                                         Direction::N  }, // 18 North-west corner of the taxiways
	{   22,   70, {},                                                                         Direction::N  }, // 19 In front of berth 1
	{   22,   54, {},                                                                         Direction::N  }, // 20 In front of berth 2
	{   22,   38, {},                                                                         Direction::N  }, // 21 In front of berth 3
	{  -50,    6, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 22 Final approach fix, runway 2
	{    6,    6, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Land},         Direction::N  }, // 23 Touch down on runway 2
	{   40,    6, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Brake},        Direction::N  }, // 24 Stop on runway 2, holding short of its departure half
	{   34,   16, {},                                                                         Direction::N  }, // 25 Leave runway 2
	{   78,   14, {},                                                                         Direction::N  }, // 26 Holding point before the departure half of runway 2
	{   64,    6, {AirportMovingDataFlag::ExactPosition},                                     Direction::SW }, // 27 Line up on runway 2
	{  109,    6, {AirportMovingDataFlag::NoSpeedClamp},                                      Direction::N  }, // 28 End of the departure run on runway 2
	{  170,    6, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Takeoff},      Direction::N  }, // 29 Take off from runway 2
	{  170,  104, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 30 Final approach fix, runway 1
	{  106,  104, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Land},         Direction::N  }, // 31 Touch down on runway 1
	{   72,  104, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Brake},        Direction::N  }, // 32 Stop on runway 1, holding short of its departure half
	{   78,   94, {},                                                                         Direction::N  }, // 33 Leave runway 1
	{   36,   94, {},                                                                         Direction::N  }, // 34 Holding point before the departure half of runway 1
	{   48,  104, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 35 Line up on runway 1
	{    3,  104, {AirportMovingDataFlag::NoSpeedClamp},                                      Direction::N  }, // 36 End of the departure run on runway 1
	{  -60,  104, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Takeoff},      Direction::N  }, // 37 Take off from runway 1
	{   60,  170, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 38 Holding (south-east)
	{  -50,  110, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 39 Holding (north-east)
	{   60,  -60, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 40 Holding (north-west)
	{  170,  -20, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 41 Holding (south-west)
};
static const uint8_t _airport_terminal_seaplane_international[] = { 2, 3, 3 };
static const uint8_t _airport_entries_seaplane_international[] = { 39, 38, 41, 40 };
static const AirportFTAbuildup _airport_fta_seaplane_international[] = {
	{  0, HANGAR, AirportBlock::Nothing, 2 }, {  0, TERMGROUP, AirportBlock::Nothing, 0 }, {  0, TERMGROUP, AirportBlock::Nothing, 1 }, {  0, TO_ALL, {}, 2 },
	{  1, HANGAR, AirportBlock::Nothing, 3 }, {  1, TERMGROUP, AirportBlock::Nothing, 1 }, {  1, TERMGROUP, AirportBlock::Nothing, 0 }, {  1, TO_ALL, {}, 3 },
	{  2, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, {  2, HANGAR, {}, 0 }, {  2, TO_ALL, {}, 19 },
	{  3, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, {  3, HANGAR, {}, 1 }, {  3, TO_ALL, {}, 15 },
	{  4, TERM1, AirportBlock::Term1, 19 },
	{  5, TERM2, AirportBlock::Term2, 20 },
	{  6, TERM3, AirportBlock::Term3, 21 },
	{  7, TERM4, AirportBlock::Term4, 13 },
	{  8, TERM5, AirportBlock::Term5, 14 },
	{  9, TERM6, AirportBlock::Term6, 15 },
	{ 10, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, { 10, TAKEOFF, {}, 34 }, { 10, TO_ALL, {}, 11 },
	{ 11, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, { 11, TO_ALL, {}, 12 },
	{ 12, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, { 12, TO_ALL, {}, 13 },
	{ 13, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, { 13, TERM4, AirportBlock::Term4, 7 }, { 13, TO_ALL, {}, 14 },
	{ 14, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, { 14, TERM5, AirportBlock::Term5, 8 }, { 14, TO_ALL, {}, 15 },
	{ 15, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, { 15, TERM6, AirportBlock::Term6, 9 }, { 15, HANGAR, {}, 3 }, { 15, TO_ALL, {}, 16 },
	{ 16, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, { 16, TAKEOFF, {}, 26 }, { 16, TO_ALL, {}, 17 },
	{ 17, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, { 17, TO_ALL, {}, 18 },
	{ 18, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, { 18, TO_ALL, {}, 21 },
	{ 19, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, { 19, TERM1, AirportBlock::Term1, 4 }, { 19, HANGAR, {}, 2 }, { 19, TO_ALL, {}, 10 },
	{ 20, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, { 20, TERM2, AirportBlock::Term2, 5 }, { 20, TO_ALL, {}, 19 },
	{ 21, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, { 21, TERM3, AirportBlock::Term3, 6 }, { 21, TO_ALL, {}, 20 },
	{ 22, FLYING, AirportBlock::Nothing, 40 }, { 22, LANDING, AirportBlock::SeaRunway2Exit, 23 },
	{ 23, LANDING, AirportBlock::SeaRunway2Land, 24 },
	{ 24, TO_ALL, AirportBlock::SeaRunway2Land, 25 },
	{ 25, ENDLANDING, AirportBlock::SeaRunway2Exit, 18 }, { 25, TERMGROUP, AirportBlock::Nothing, 0 }, { 25, TERMGROUP, AirportBlock::Nothing, 1 }, { 25, TO_ALL, {}, 18 },
	{ 26, TO_ALL, AirportBlock::SeaHold2, 27 },
	{ 27, TAKEOFF, AirportBlock::SeaRunway2Depart, 28 },
	{ 28, STARTTAKEOFF, AirportBlock::SeaRunway2Depart, 29 },
	{ 29, ENDTAKEOFF, AirportBlock::Nothing, 0 },
	{ 30, FLYING, AirportBlock::Nothing, 38 }, { 30, LANDING, AirportBlock::SeaRunway1Exit, 31 },
	{ 31, LANDING, AirportBlock::SeaRunway1Land, 32 },
	{ 32, TO_ALL, AirportBlock::SeaRunway1Land, 33 },
	{ 33, ENDLANDING, AirportBlock::SeaRunway1Exit, 12 }, { 33, TERMGROUP, AirportBlock::Nothing, 1 }, { 33, TERMGROUP, AirportBlock::Nothing, 0 }, { 33, TO_ALL, {}, 12 },
	{ 34, TO_ALL, AirportBlock::SeaHold1, 35 },
	{ 35, TAKEOFF, AirportBlock::SeaRunway1Depart, 36 },
	{ 36, STARTTAKEOFF, AirportBlock::SeaRunway1Depart, 37 },
	{ 37, ENDTAKEOFF, AirportBlock::Nothing, 0 },
	{ 38, TO_ALL, AirportBlock::Nothing, 39 },
	{ 39, TO_ALL, AirportBlock::Nothing, 22 },
	{ 40, TO_ALL, AirportBlock::Nothing, 41 },
	{ 41, TO_ALL, AirportBlock::Nothing, 30 },
	{ MAX_ELEMENTS, TO_ALL, {}, 0 } // end marker. DO NOT REMOVE
};

/** Seaplane dock. */
static const AirportMovingData _airport_moving_data_seaplane_dock[13] = {
	{   10,   16, {AirportMovingDataFlag::ExactPosition},                                     Direction::NW }, // 00 Berth
	{   20,   10, {},                                                                         Direction::N  }, // 01 Leave the berth
	{   24,   20, {AirportMovingDataFlag::ExactPosition},                                     Direction::NW }, // 02 Line up: start of the departure half
	{   24,   -4, {AirportMovingDataFlag::NoSpeedClamp},                                      Direction::N  }, // 03 End of the departure run
	{   24,  -60, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Takeoff},      Direction::N  }, // 04 Take off
	{   24,  110, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 05 Final approach fix
	{   24,   46, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Land},         Direction::N  }, // 06 Touch down
	{   24,   26, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Brake},        Direction::N  }, // 07 Stop, holding short of the departure half
	{   18,   22, {},                                                                         Direction::N  }, // 08 Leave the water lane
	{  110,    0, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 09 Holding (south-west)
	{  -10,    0, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 10 Holding (north-west)
	{  -10,  150, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 11 Holding (north-east)
	{   40,  160, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 12 Holding (south-east)
};
static const uint8_t _airport_terminal_seaplane_dock[] = { 1, 1 };
static const uint8_t _airport_entries_seaplane_dock[] = { 10, 11, 9, 10 };
static const AirportFTAbuildup _airport_fta_seaplane_dock[] = {
	{  0, TERM1, AirportBlock::Term1, 1 },
	{  1, TO_ALL, AirportBlock::SeaHold1, 2 },
	{  2, TAKEOFF, AirportBlock::SeaRunway1Depart, 3 },
	{  3, STARTTAKEOFF, AirportBlock::SeaRunway1Depart, 4 },
	{  4, ENDTAKEOFF, AirportBlock::Nothing, 0 },
	{  5, FLYING, AirportBlock::Nothing, 9 }, {  5, LANDING, AirportBlocks({AirportBlock::Term1, AirportBlock::SeaRunway1Exit}), 6 },
	{  6, LANDING, AirportBlock::SeaRunway1Land, 7 },
	{  7, TO_ALL, AirportBlock::SeaRunway1Land, 8 },
	{  8, ENDLANDING, AirportBlock::SeaRunway1Exit, 0 }, {  8, TERM1, AirportBlock::Term1, 0 }, {  8, TAKEOFF, {}, 1 }, {  8, TO_ALL, {}, 1 },
	{  9, TO_ALL, AirportBlock::Nothing, 10 },
	{ 10, TO_ALL, AirportBlock::Nothing, 11 },
	{ 11, TO_ALL, AirportBlock::Nothing, 12 },
	{ 12, TO_ALL, AirportBlock::Nothing, 5 },
	{ MAX_ELEMENTS, TO_ALL, {}, 0 } // end marker. DO NOT REMOVE
};

/** Seaplane kerb dock. */
static const AirportMovingData _airport_moving_data_seaplane_kerb[29] = {
	{   84,   12, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 00 Slot 1 alongside the dock
	{   73,   12, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 01 Slot 2 alongside the dock
	{   62,   12, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 02 Slot 3 alongside the dock
	{   51,   12, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 03 Slot 4 alongside the dock
	{   40,   12, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 04 Slot 5 alongside the dock
	{   29,   12, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 05 Slot 6 alongside the dock
	{   18,   12, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 06 Slot 7 alongside the dock
	{    7,   12, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 07 Slot 8 alongside the dock
	{   92,   24, {},                                                                         Direction::N  }, // 08 Lane beside slot 1
	{   81,   24, {},                                                                         Direction::N  }, // 09 Lane beside slot 2
	{   70,   24, {},                                                                         Direction::N  }, // 10 Lane beside slot 3
	{   59,   24, {},                                                                         Direction::N  }, // 11 Lane beside slot 4
	{   48,   24, {},                                                                         Direction::N  }, // 12 Lane beside slot 5
	{   37,   24, {},                                                                         Direction::N  }, // 13 Lane beside slot 6
	{   26,   24, {},                                                                         Direction::N  }, // 14 Lane beside slot 7
	{   15,   24, {},                                                                         Direction::N  }, // 15 Lane beside slot 8
	{    4,   24, {},                                                                         Direction::N  }, // 16 North-east end of the lane
	{    4,   40, {},                                                                         Direction::N  }, // 17 Enter the departure half
	{   46,   40, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 18 Line up: start of the departure half
	{    2,   40, {AirportMovingDataFlag::NoSpeedClamp},                                      Direction::N  }, // 19 End of the departure run
	{  -50,   40, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Takeoff},      Direction::N  }, // 20 Take off
	{  140,   40, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 21 Final approach fix
	{   92,   40, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Land},         Direction::N  }, // 22 Touch down at the start of the landing half
	{   54,   40, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Brake},        Direction::N  }, // 23 Stop, holding short of the departure half
	{   72,   32, {},                                                                         Direction::N  }, // 24 Leave the landing half for the lane
	{   10,  130, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 25 Holding (north-east)
	{   10,  -20, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 26 Holding (north-west)
	{  150,  -20, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 27 Holding (south-west)
	{  170,   30, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 28 Holding (south)
};
static const uint8_t _airport_terminal_seaplane_kerb[] = { 1, 8 };
static const uint8_t _airport_entries_seaplane_kerb[] = { 26, 25, 28, 27 };
static const AirportFTAbuildup _airport_fta_seaplane_kerb[] = {
	{  0, TERM1, AirportBlock::Term1, 9 },
	{  1, TERM2, AirportBlock::Term2, 10 },
	{  2, TERM3, AirportBlock::Term3, 11 },
	{  3, TERM4, AirportBlock::Term4, 12 },
	{  4, TERM5, AirportBlock::Term5, 13 },
	{  5, TERM6, AirportBlock::Term6, 14 },
	{  6, TERM7, AirportBlock::Term7, 15 },
	{  7, TERM8, AirportBlock::Term8, 16 },
	{  8, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, {  8, TERM1, AirportBlock::Term1, 0 }, {  8, TO_ALL, {}, 9 },
	{  9, TERMGROUP, AirportBlock::SeaTaxi2, 0 }, {  9, TERM2, AirportBlock::Term2, 1 }, {  9, TO_ALL, {}, 10 },
	{ 10, TERMGROUP, AirportBlock::SeaTaxi3, 0 }, { 10, TERM3, AirportBlock::Term3, 2 }, { 10, TO_ALL, {}, 11 },
	{ 11, TERMGROUP, AirportBlock::SeaTaxi4, 0 }, { 11, TERM4, AirportBlock::Term4, 3 }, { 11, TO_ALL, {}, 12 },
	{ 12, TERMGROUP, AirportBlock::SeaTaxi5, 0 }, { 12, TERM5, AirportBlock::Term5, 4 }, { 12, TO_ALL, {}, 13 },
	{ 13, TERMGROUP, AirportBlock::SeaTaxi6, 0 }, { 13, TERM6, AirportBlock::Term6, 5 }, { 13, TO_ALL, {}, 14 },
	{ 14, TERMGROUP, AirportBlock::SeaTaxi7, 0 }, { 14, TERM7, AirportBlock::Term7, 6 }, { 14, TO_ALL, {}, 15 },
	{ 15, TERMGROUP, AirportBlock::SeaTaxi8, 0 }, { 15, TERM8, AirportBlock::Term8, 7 }, { 15, TO_ALL, {}, 16 },
	{ 16, TO_ALL, AirportBlock::SeaHold1, 17 },
	{ 17, TO_ALL, AirportBlock::SeaRunway1Depart, 18 },
	{ 18, TAKEOFF, AirportBlock::SeaRunway1Depart, 19 },
	{ 19, STARTTAKEOFF, AirportBlock::SeaRunway1Depart, 20 },
	{ 20, ENDTAKEOFF, AirportBlock::Nothing, 0 },
	{ 21, FLYING, AirportBlock::Nothing, 25 }, { 21, LANDING, AirportBlock::SeaRunway1Exit, 22 },
	{ 22, LANDING, AirportBlock::SeaRunway1Land, 23 },
	{ 23, TO_ALL, AirportBlock::SeaRunway1Land, 24 },
	{ 24, ENDLANDING, AirportBlock::SeaRunway1Exit, 8 }, { 24, TO_ALL, {}, 8 },
	{ 25, TO_ALL, AirportBlock::Nothing, 26 },
	{ 26, TO_ALL, AirportBlock::Nothing, 27 },
	{ 27, TO_ALL, AirportBlock::Nothing, 28 },
	{ 28, TO_ALL, AirportBlock::Nothing, 21 },
	{ MAX_ELEMENTS, TO_ALL, {}, 0 } // end marker. DO NOT REMOVE
};

/** Seaplane kerb terminal with hangar. */
static const AirportMovingData _airport_moving_data_seaplane_kerb_hangar[27] = {
	{    7,    3, {AirportMovingDataFlag::ExactPosition},                                     Direction::SE }, // 00 In hangar
	{   70,   29, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 01 Slot 1 alongside the dock
	{   59,   29, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 02 Slot 2 alongside the dock
	{   48,   29, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 03 Slot 3 alongside the dock
	{   37,   29, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 04 Slot 4 alongside the dock
	{   26,   29, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 05 Slot 5 alongside the dock
	{   76,   41, {},                                                                         Direction::N  }, // 06 Lane beside slot 1
	{   65,   41, {},                                                                         Direction::N  }, // 07 Lane beside slot 2
	{   54,   41, {},                                                                         Direction::N  }, // 08 Lane beside slot 3
	{   43,   41, {},                                                                         Direction::N  }, // 09 Lane beside slot 4
	{   32,   41, {},                                                                         Direction::N  }, // 10 Lane beside slot 5
	{   14,   41, {},                                                                         Direction::N  }, // 11 North-east end of the lane
	{    8,   24, {},                                                                         Direction::N  }, // 12 Outside the hangar
	{    6,   56, {},                                                                         Direction::N  }, // 13 Enter the departure half
	{   38,   56, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 14 Line up: start of the departure half
	{    2,   56, {AirportMovingDataFlag::NoSpeedClamp},                                      Direction::N  }, // 15 End of the departure run
	{  -50,   56, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Takeoff},      Direction::N  }, // 16 Take off
	{  130,   56, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 17 Final approach fix
	{   76,   56, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Land},         Direction::N  }, // 18 Touch down at the start of the landing half
	{   44,   56, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Brake},        Direction::N  }, // 19 Stop, holding short of the departure half
	{   66,   48, {},                                                                         Direction::N  }, // 20 Leave the landing half for the lane
	{    4,   47, {},                                                                         Direction::N  }, // 21 Return path from the hangar
	{   58,   48, {},                                                                         Direction::N  }, // 22 Return path to the lane
	{   10,  130, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 23 Holding (north-east)
	{   10,  -20, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 24 Holding (north-west)
	{  150,  -20, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 25 Holding (south-west)
	{  170,   40, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 26 Holding (south)
};
static const HangarTileTable _airport_depots_seaplane_kerb_hangar[] = { {{0, 0}, Direction::SE, 0} };
static const uint8_t _airport_terminal_seaplane_kerb_hangar[] = { 1, 5 };
static const uint8_t _airport_entries_seaplane_kerb_hangar[] = { 24, 23, 26, 25 };
static const AirportFTAbuildup _airport_fta_seaplane_kerb_hangar[] = {
	{  0, HANGAR, AirportBlock::Nothing, 12 },
	{  1, TERM1, AirportBlock::Term1, 7 },
	{  2, TERM2, AirportBlock::Term2, 8 },
	{  3, TERM3, AirportBlock::Term3, 9 },
	{  4, TERM4, AirportBlock::Term4, 10 },
	{  5, TERM5, AirportBlock::Term5, 11 },
	{  6, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, {  6, TERM1, AirportBlock::Term1, 1 }, {  6, TO_ALL, {}, 7 },
	{  7, TERMGROUP, AirportBlock::SeaTaxi2, 0 }, {  7, TERM2, AirportBlock::Term2, 2 }, {  7, TO_ALL, {}, 8 },
	{  8, TERMGROUP, AirportBlock::SeaTaxi3, 0 }, {  8, TERM3, AirportBlock::Term3, 3 }, {  8, TO_ALL, {}, 9 },
	{  9, TERMGROUP, AirportBlock::SeaTaxi4, 0 }, {  9, TERM4, AirportBlock::Term4, 4 }, {  9, TO_ALL, {}, 10 },
	{ 10, TERMGROUP, AirportBlock::SeaTaxi5, 0 }, { 10, TERM5, AirportBlock::Term5, 5 }, { 10, TO_ALL, {}, 11 },
	{ 11, TERMGROUP, AirportBlock::SeaHold1, 0 }, { 11, HANGAR, {}, 0 }, { 11, TO_ALL, {}, 13 },
	{ 12, TERMGROUP, AirportBlock::Hangar1Area, 0 }, { 12, TAKEOFF, {}, 13 }, { 12, HANGAR, {}, 0 }, { 12, TO_ALL, {}, 21 },
	{ 13, TO_ALL, AirportBlock::SeaRunway1Depart, 14 },
	{ 14, TAKEOFF, AirportBlock::SeaRunway1Depart, 15 },
	{ 15, STARTTAKEOFF, AirportBlock::SeaRunway1Depart, 16 },
	{ 16, ENDTAKEOFF, AirportBlock::Nothing, 1 },
	{ 17, FLYING, AirportBlock::Nothing, 23 }, { 17, LANDING, AirportBlock::SeaRunway1Exit, 18 },
	{ 18, LANDING, AirportBlock::SeaRunway1Land, 19 },
	{ 19, TO_ALL, AirportBlock::SeaRunway1Land, 20 },
	{ 20, ENDLANDING, AirportBlock::SeaRunway1Exit, 6 }, { 20, TO_ALL, {}, 6 },
	{ 21, TO_ALL, AirportBlock::SeaTaxi6, 22 },
	{ 22, TO_ALL, AirportBlock::SeaTaxi6, 20 },
	{ 23, TO_ALL, AirportBlock::Nothing, 24 },
	{ 24, TO_ALL, AirportBlock::Nothing, 25 },
	{ 25, TO_ALL, AirportBlock::Nothing, 26 },
	{ 26, TO_ALL, AirportBlock::Nothing, 17 },
	{ MAX_ELEMENTS, TO_ALL, {}, 0 } // end marker. DO NOT REMOVE
};

/** Large seaplane kerb terminal. */
static const AirportMovingData _airport_moving_data_seaplane_kerb_large[46] = {
	{  103,   19, {AirportMovingDataFlag::ExactPosition},                                     Direction::SE }, // 00 In the north hangar
	{  103,   83, {AirportMovingDataFlag::ExactPosition},                                     Direction::SE }, // 01 In the south hangar
	{   92,   44, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 02 Slot 1 alongside the dock
	{   74,   44, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 03 Slot 2 alongside the dock
	{   56,   44, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 04 Slot 3 alongside the dock
	{   38,   44, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 05 Slot 4 alongside the dock
	{  100,   32, {},                                                                         Direction::N  }, // 06 Lane beside slot 1
	{   82,   32, {},                                                                         Direction::N  }, // 07 Lane beside slot 2
	{   64,   32, {},                                                                         Direction::N  }, // 08 Lane beside slot 3
	{   46,   32, {},                                                                         Direction::N  }, // 09 Lane beside slot 4
	{   20,   68, {AirportMovingDataFlag::ExactPosition},                                     Direction::SW }, // 10 Slot 5 alongside the dock
	{   38,   68, {AirportMovingDataFlag::ExactPosition},                                     Direction::SW }, // 11 Slot 6 alongside the dock
	{   56,   68, {AirportMovingDataFlag::ExactPosition},                                     Direction::SW }, // 12 Slot 7 alongside the dock
	{   74,   68, {AirportMovingDataFlag::ExactPosition},                                     Direction::SW }, // 13 Slot 8 alongside the dock
	{   12,   80, {},                                                                         Direction::N  }, // 14 Lane beside slot 5
	{   30,   80, {},                                                                         Direction::N  }, // 15 Lane beside slot 6
	{   48,   80, {},                                                                         Direction::N  }, // 16 Lane beside slot 7
	{   66,   80, {},                                                                         Direction::N  }, // 17 Lane beside slot 8
	{   24,   32, {},                                                                         Direction::N  }, // 18 North lane: north-east end
	{    8,    8, {},                                                                         Direction::N  }, // 19 Enter the departure half of the north runway
	{   56,    8, {AirportMovingDataFlag::ExactPosition},                                     Direction::NE }, // 20 Line up on the north runway
	{    2,    8, {AirportMovingDataFlag::NoSpeedClamp},                                      Direction::N  }, // 21 End of the departure run, north runway
	{  -50,    8, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Takeoff},      Direction::N  }, // 22 Take off from the north runway
	{  170,    8, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 23 Final approach fix, north runway
	{  106,    8, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Land},         Direction::N  }, // 24 Touch down on the north runway
	{   64,    8, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Brake},        Direction::N  }, // 25 Stop on the north runway, holding short
	{   84,   20, {},                                                                         Direction::N  }, // 26 Leave the north runway for the north lane
	{  106,   38, {},                                                                         Direction::N  }, // 27 Outside the north hangar
	{   20,   22, {},                                                                         Direction::N  }, // 28 Path to the north hangar
	{   92,   24, {},                                                                         Direction::N  }, // 29 Path to the north hangar
	{   90,   80, {},                                                                         Direction::N  }, // 30 South lane: south-west end
	{  106,  104, {},                                                                         Direction::N  }, // 31 Enter the departure half of the south runway
	{   56,  104, {AirportMovingDataFlag::ExactPosition},                                     Direction::SW }, // 32 Line up on the south runway
	{  110,  104, {AirportMovingDataFlag::NoSpeedClamp},                                      Direction::N  }, // 33 End of the departure run, south runway
	{  170,  104, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Takeoff},      Direction::N  }, // 34 Take off from the south runway
	{  -60,  104, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 35 Final approach fix, south runway
	{    6,  104, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Land},         Direction::N  }, // 36 Touch down on the south runway
	{   48,  104, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::Brake},        Direction::N  }, // 37 Stop on the south runway, holding short
	{   28,   92, {},                                                                         Direction::N  }, // 38 Leave the south runway for the south lane
	{  104,   96, {},                                                                         Direction::N  }, // 39 Outside the south hangar
	{   90,   92, {},                                                                         Direction::N  }, // 40 Return path from the south hangar
	{    8,   90, {},                                                                         Direction::N  }, // 41 Return path to the south lane
	{   60,  -60, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 42 Holding (north-west)
	{  -60,   40, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 43 Holding (north-east)
	{   60,  170, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 44 Holding (south-east)
	{  170,   70, {AirportMovingDataFlag::NoSpeedClamp, AirportMovingDataFlag::SlowTurn},     Direction::N  }, // 45 Holding (south-west)
};
static const HangarTileTable _airport_depots_seaplane_kerb_large[] = { {{6, 1}, Direction::SE, 0}, {{6, 5}, Direction::SE, 1} };
static const uint8_t _airport_terminal_seaplane_kerb_large[] = { 2, 4, 4 };
static const uint8_t _airport_entries_seaplane_kerb_large[] = { 43, 44, 45, 42 };
static const AirportFTAbuildup _airport_fta_seaplane_kerb_large[] = {
	{  0, HANGAR, AirportBlock::Nothing, 27 }, {  0, TERMGROUP, AirportBlock::Nothing, 0 }, {  0, TO_ALL, {}, 27 },
	{  1, HANGAR, AirportBlock::Nothing, 39 }, {  1, TERMGROUP, AirportBlock::Nothing, 1 }, {  1, TO_ALL, {}, 39 },
	{  2, TERM1, AirportBlock::Term1, 7 },
	{  3, TERM2, AirportBlock::Term2, 8 },
	{  4, TERM3, AirportBlock::Term3, 9 },
	{  5, TERM4, AirportBlock::Term4, 18 },
	{  6, TERMGROUP, AirportBlock::SeaTaxi1, 0 }, {  6, TERM1, AirportBlock::Term1, 2 }, {  6, TO_ALL, {}, 7 },
	{  7, TERMGROUP, AirportBlock::SeaTaxi2, 0 }, {  7, TERM2, AirportBlock::Term2, 3 }, {  7, TO_ALL, {}, 8 },
	{  8, TERMGROUP, AirportBlock::SeaTaxi3, 0 }, {  8, TERM3, AirportBlock::Term3, 4 }, {  8, TO_ALL, {}, 9 },
	{  9, TERMGROUP, AirportBlock::SeaTaxi4, 0 }, {  9, TERM4, AirportBlock::Term4, 5 }, {  9, TO_ALL, {}, 18 },
	{ 10, TERM5, AirportBlock::Term5, 15 },
	{ 11, TERM6, AirportBlock::Term6, 16 },
	{ 12, TERM7, AirportBlock::Term7, 17 },
	{ 13, TERM8, AirportBlock::Term8, 30 },
	{ 14, TERMGROUP, AirportBlock::SeaTaxi5, 0 }, { 14, TERM5, AirportBlock::Term5, 10 }, { 14, TO_ALL, {}, 15 },
	{ 15, TERMGROUP, AirportBlock::SeaTaxi6, 0 }, { 15, TERM6, AirportBlock::Term6, 11 }, { 15, TO_ALL, {}, 16 },
	{ 16, TERMGROUP, AirportBlock::SeaTaxi7, 0 }, { 16, TERM7, AirportBlock::Term7, 12 }, { 16, TO_ALL, {}, 17 },
	{ 17, TERMGROUP, AirportBlock::SeaTaxi8, 0 }, { 17, TERM8, AirportBlock::Term8, 13 }, { 17, TO_ALL, {}, 30 },
	{ 18, TERMGROUP, AirportBlock::SeaHold2, 0 }, { 18, HANGAR, {}, 28 }, { 18, TO_ALL, {}, 19 },
	{ 19, TO_ALL, AirportBlock::SeaRunway2Depart, 20 },
	{ 20, TAKEOFF, AirportBlock::SeaRunway2Depart, 21 },
	{ 21, STARTTAKEOFF, AirportBlock::SeaRunway2Depart, 22 },
	{ 22, ENDTAKEOFF, AirportBlock::Nothing, 2 },
	{ 23, FLYING, AirportBlock::Nothing, 42 }, { 23, LANDING, AirportBlock::SeaRunway2Exit, 24 },
	{ 24, LANDING, AirportBlock::SeaRunway2Land, 25 },
	{ 25, TO_ALL, AirportBlock::SeaRunway2Land, 26 },
	{ 26, ENDLANDING, AirportBlock::SeaRunway2Exit, 6 }, { 26, TERMGROUP, AirportBlock::Nothing, 0 }, { 26, TO_ALL, {}, 6 },
	{ 27, TERMGROUP, AirportBlock::Hangar1Area, 0 }, { 27, HANGAR, {}, 0 }, { 27, TO_ALL, {}, 6 },
	{ 28, TO_ALL, AirportBlock::SeaTaxi9, 29 },
	{ 29, TO_ALL, AirportBlock::SeaTaxi9, 0 },
	{ 30, TERMGROUP, AirportBlock::SeaHold1, 0 }, { 30, HANGAR, {}, 1 }, { 30, TO_ALL, {}, 31 },
	{ 31, TO_ALL, AirportBlock::SeaRunway1Depart, 32 },
	{ 32, TAKEOFF, AirportBlock::SeaRunway1Depart, 33 },
	{ 33, STARTTAKEOFF, AirportBlock::SeaRunway1Depart, 34 },
	{ 34, ENDTAKEOFF, AirportBlock::Nothing, 2 },
	{ 35, FLYING, AirportBlock::Nothing, 44 }, { 35, LANDING, AirportBlock::SeaRunway1Exit, 36 },
	{ 36, LANDING, AirportBlock::SeaRunway1Land, 37 },
	{ 37, TO_ALL, AirportBlock::SeaRunway1Land, 38 },
	{ 38, ENDLANDING, AirportBlock::SeaRunway1Exit, 14 }, { 38, TERMGROUP, AirportBlock::Nothing, 1 }, { 38, TO_ALL, {}, 14 },
	{ 39, TERMGROUP, AirportBlock::Hangar2Area, 0 }, { 39, TAKEOFF, {}, 31 }, { 39, HANGAR, {}, 1 }, { 39, TO_ALL, {}, 40 },
	{ 40, TO_ALL, AirportBlock::SeaTaxi10, 41 },
	{ 41, TO_ALL, AirportBlock::SeaTaxi10, 14 },
	{ 42, TO_ALL, AirportBlock::Nothing, 43 },
	{ 43, TO_ALL, AirportBlock::Nothing, 35 },
	{ 44, TO_ALL, AirportBlock::Nothing, 45 },
	{ 45, TO_ALL, AirportBlock::Nothing, 23 },
	{ MAX_ELEMENTS, TO_ALL, {}, 0 } // end marker. DO NOT REMOVE
};

#endif /* SEAPLANE_MOVEMENT_H */
